Tiger technique
ProjectStarlight/StarlightRiver pull request #201
Opened 2022-07-21 01:13 UTC by ScalarVector1

###What are the specifics of what is being added?
The tiger technique accessory, which allows the execution of custom combos with axes.

###Is there an associated suggestion or dev server #code-needed post? How well does this PR follow it?
https://trello.com/c/uqrAW6ek/118-tiger-technique-5

###Is there anything left to be done in this addition?
Obtainment methods to be done as a separate ticket.

2023-01-24 14:58 UTC, ScalarVector1 commented on Content/Items/Misc/Accessories.AxeBook.cs
> +		public override string Texture => AssetDirectory.MiscItem + "AxeBook";
property override should be before ctor

2023-03-26 07:28 UTC, TripleFate requested changes

2023-03-26 07:28 UTC, TripleFate commented on Content/Items/Misc/Accessories.AxeBook.cs
> +		private bool OverrideAxeEffects(Item item, Player player)
This probably shouldn't entirely override axe functionality. I would expect to still be able to chop trees down with this equipped

2023-03-26 07:28 UTC, TripleFate commented on Content/Items/Misc/Accessories.AxeBook.cs
> +		public AxeBook() : base("Tiger Technique", "Allows execution of combos with axes\nThe final strike will rend enemy armor\nRight click to throw your axe") { }
We really need some kind of expanded tooltips,. When I see this I wonder if this rend effect is good. I'd want to know things like if this debuff stacks, how much it reduces the armor by (which we should probably stay consistent with vanilla and call it defense anyway) how long it lasts. Vanilla is also really bad about this, requiring you to go to the wiki to actually determine if an item is good but we could be better

2023-03-26 07:28 UTC, TripleFate commented on Content/Items/Misc/Accessories.AxeBook.cs
> +					//Helper.PlayPitched("ChainHit", 1, pitch, player.Center);
remove comment

2023-03-27 18:59 UTC, merged