Loot wraith
ProjectStarlight/StarlightRiver pull request #384
Opened 2023-04-11 00:14 UTC by ThatDamnPineapple

What are the specifics of what is being added?
The loot wraith, an enemy that sometimes spawns attached to chests

Is there an associated suggestion or dev server #code-needed post? How well does this PR follow it?
https://trello.com/c/z09Ylqnv/239-loot-wraith-25
Follows it to a T

Is there anything left to be done in this addition?
The enemy still wants a loot drop (I don't remember exactly what the loot drop was)
An animation (which I can't request myself for obvious reasons)
Still needs to be nettable (I don't remember the exact plans around this)
And it needs dash sound effects (This should be easy enough to add)

Despite these, it is release ready as is in my opinion

2023-04-11 00:27 UTC, ThatDamnPineapple commented
All the errors found are either going to change once the animation is implemented, or to remove parenthesis that help make it more readable.

2023-04-12 17:09 UTC, ScalarVector1 requested changes
It seems like there may be some redundant code related to a second trail that is never rendered in the loot wraith NPC. We should remove this. Additionally I have a few concerns about the world generation logic

2023-04-12 17:09 UTC, ScalarVector1 commented on Content/NPCs/Misc/LootWraith.cs
> +						if (NPC.velocity == Vector2.Zero)
single line conditionals should be inlined

2023-04-12 17:09 UTC, ScalarVector1 commented on Content/NPCs/Misc/LootWraith.cs
> +			if (chain is null || NPC.DistanceSQ(Target.Center) > 4000000 || enraged)
This seems like a rather large number to check against -- is this arbitrary? Should we set it lower?

2023-04-12 17:09 UTC, ScalarVector1 commented on Content/NPCs/Misc/LootWraith.cs
> +			Main.spriteBatch.End();
Whats with the spriteBatch restart here?

2023-04-12 17:09 UTC, ScalarVector1 commented on Content/NPCs/Misc/LootWraith.cs
> +			//trail2?.Render(effect);
if trail2 is never rendered, why are we updating it? Is this fully unused? If so, the update code for it should be removed.

2023-04-12 17:09 UTC, ScalarVector1 commented on Content/WorldGeneration/GenerateLootWraiths.cs
> +				if (chest != null && Main.rand.NextBool(15))
Should we maybe yield the random check untill after we determine this is the correct type of chest? Seems redundant to roll it on every chest then check the type afterwards

2023-04-12 17:09 UTC, ScalarVector1 commented on Content/WorldGeneration/GenerateLootWraiths.cs
> +				if (chest != null && Main.rand.NextBool(15))
Also, we should be using the world gen random here, not Main.rand so that this behavior is consistent across seeds!

2023-04-12 17:09 UTC, ScalarVector1 commented on Content/WorldGeneration/WorldgenWorld.cs
> +				tasks.Insert(DesertIndex + 2, new PassLegacy("Starlight River Permafrost", PermafrostGen));
Why are these duplicate lines here?

2023-04-12 17:09 UTC, ScalarVector1 commented on Effects/Compile/RepeatingChain.fx
> +﻿float alpha;
Lets make sure we dont commit things in the compile folder

2023-07-08 17:03 UTC, merged