Slime prince armor
ProjectStarlight/StarlightRiver pull request #603
Opened 2023-07-20 03:08 UTC by ScalarVector1

This PR introduces the slime prince armor, as well as some general minion targeting utilities. It also includes an emergency fix to the tentalance because oops!

2023-07-20 03:16 UTC, TripleFate commented on Content/Items/Permafrost/Weapons.Tentalance.cs
> -			if (!player.channel)
use the changes in #604 over these

2023-07-20 03:35 UTC, ScalarVector1 commented on Content/Items/Permafrost/Weapons.Tentalance.cs
> -			if (!player.channel)
should be merged in correctly now

2023-07-20 03:53 UTC, TripleFate approved these changes
Approving in case you don't want to make these changes but I think we should really try to have things be multiplayer compatible as they're made instead of later passes

2023-07-20 03:53 UTC, TripleFate commented on Content/Items/Forest/Armors.SlimePrince.cs
> +				prince = Projectile.NewProjectileDirect(player.GetSource_FromThis(), player.Center, Vector2.Zero, ProjectileType<SlimePrinceMinion>(), 28, 0, player.whoAmI);
gonna start calling out more multiplayer compatibility stuff:
the prince variable will only get assigned to by the wearer of the helm so everything that tries to access 
SlimePrinceHead.Minion needs to be functionally owner only or this needs to get sent as a packet or searched for by the other clients and server

2023-07-20 03:53 UTC, TripleFate commented on Content/Items/Forest/Armors.SlimePrinceMinion.cs
> +			if (Vector2.Distance(Projectile.Center, Owner.Center) > 5000)
good situation to have a netupdate = true, since it's rare and involves a drastic position change. even though its technically deterministic

2023-07-20 03:53 UTC, TripleFate commented on Content/Items/Forest/Armors.SlimePrinceMinion.cs
> +				Projectile.NewProjectile(Projectile.GetSource_FromThis(), Projectile.Center, Projectile.Center.DirectionTo(target.Center + target.velocity * 10) * 11, ModContent.ProjectileType<SlimeThorn>(), 20,
Projectile.newProjectile needs to run for only one client or the server but not all otherwise it'll duplicate

2023-07-20 03:53 UTC, TripleFate commented on Content/Items/Forest/Armors.SlimePrinceMinion.cs
> +					Projectile.NewProjectile(Projectile.GetSource_FromThis(), Projectile.Center, Projectile.Center.DirectionTo(target.Center) * 11, ModContent.ProjectileType<SlimeThorn>(), 35, 0.5f, Projectile.owne
same comment about newProjectile being called too much by other clients

2023-07-20 03:53 UTC, TripleFate commented on Content/Items/Forest/Armors.SlimePrince.cs
> +		private void ActivateMerge(On_Player.orig_KeyDoubleTap orig, Player self, int keyDir)
I'd have to test to be sure but I feel like this would need a packet

2023-07-20 03:53 UTC, TripleFate commented on Content/Items/Forest/Armors.SlimePrince.cs
> +		private bool AbosrbSlime(Player player, Player.HurtInfo info)
"Absorb" typo

2023-07-20 03:53 UTC, TripleFate commented on Content/Items/Forest/Armors.SlimePrince.cs
> +		private void InflictExposure(Projectile projectile, NPC target, NPC.HitInfo hit, int damageDone)
good candidate for using the new StarlightPlayer.SetHitPacketStatus(true) though the StarlightProjectile.Onhit events are new to me and not handled by it (do we really use the processing order in any meaningful capacity that it needs to be split?)

2023-07-20 03:54 UTC, TripleFate commented on Content/Items/Forest/Armors.SlimePrince.cs
> +		private void InflictExposure(Projectile projectile, NPC target, NPC.HitInfo hit, int damageDone)
correction on this one: it wouldn't need to be set to true in the params since this would be on the event not via a projectile's override

2023-07-22 03:19 UTC, TripleFate requested changes

2023-07-22 03:19 UTC, TripleFate commented on Content/Items/Forest/Armors.SlimePrince.cs
> +			if (prince is null || !prince.active || prince.type != ProjectileType<SlimePrinceMinion>() || prince.owner != player.whoAmI)
this gets executed by clients that aren't the prince owner if the prince is null too potentially making extra

2023-07-22 03:19 UTC, TripleFate commented on Content/Items/Forest/Armors.SlimePrinceMinion.cs
> +			if (Timer == 110 && Main.netMode != NetmodeID.Server)
this gets executed by other clients too 1 for every player needs to check against myplayer

2023-07-22 03:19 UTC, TripleFate commented on Content/Items/Forest/Armors.SlimePrinceMinion.cs
> +			if (Timer == 110 && Main.netMode != NetmodeID.Server)
but keep the sound like this too or put it into the first frame of the projectile

2023-07-22 03:19 UTC, TripleFate commented on Content/Items/Forest/Armors.SlimePrinceMinion.cs
> +			if (Timer % 30 == 0 && Main.netMode != NetmodeID.Server)
same issue this needs to check against myplayer when spawning the projectile but this is good for the playsound part

2023-07-22 04:11 UTC, TripleFate approved these changes
not certain without testing it myself but I don't see any of the common gotchas for multiplayer anymore

2023-07-22 04:16 UTC, merged