minor changes + forbidden winds sound effect
ProjectStarlight/StarlightRiver pull request #642
Opened 2023-08-06 04:31 UTC by sbubby

Replaces the sound effect for obtaining forbidden winds.
Replaces the shrine of combat skeleton archers with hoplites.
Added to the description of the Hermes vow.
Added Crafting recipes for desert monoliths.

2023-08-06 15:57 UTC, ScalarVector1 requested changes
Please fix formatting and update PATCH_NOTES.txt

2023-08-06 15:57 UTC, ScalarVector1 commented on Content/Tiles/Desert/DesertMonolith.cs
> +		public override void AddRecipes()
missing linebreak

2023-08-06 15:57 UTC, ScalarVector1 commented on Content/Tiles/Desert/DesertMonolith.cs
> +		public override void AddRecipes()
missing linebreak

2023-08-06 21:59 UTC, sbubby commented
i wasn't sure where to put the desert monolith recipe in the patch notes

2023-08-07 03:02 UTC, ScalarVector1 approved these changes

2023-08-07 03:04 UTC, merged