General Polish
ProjectStarlight/StarlightRiver pull request #693
Opened 2024-02-24 03:18 UTC by SkippZzMods

Polishes the VFX and in some cases gameplay of various content that isn't up to date

2025-01-17 02:12 UTC, ScalarVector1 requested changes

2025-01-17 02:12 UTC, ScalarVector1 commented on Content/Dusts/Glow.cs
> +	public class PixelatedGlow : ModDust
Do these behaviors differ from the other Glow dusts? Could this just be parented with an override in predraw?

2025-01-17 02:12 UTC, ScalarVector1 commented on Content/Items/Breacher/Weapons.FlareBreacher.cs
> +			Texture2D tex = ModContent.Request<Texture2D>(AssetDirectory.BreacherItem  + Name).Value;
This all needs to be changed to the AssGen assets, this will cause severe memory usage especially on a dust

2025-01-17 02:12 UTC, ScalarVector1 commented on Content/Items/Dungeon/Weapons.SkullBuster.cs
> +			Texture2D tex = ModContent.Request<Texture2D>(AssetDirectory.DungeonItem + Name).Value;
Same as above, needs to use the AssGen assets

2025-01-17 02:12 UTC, ScalarVector1 commented on Content/Items/Misc/SoilgunFiles/Weapons.Soilgun.cs
> +			Tooltip.SetDefault("Hold <left> to charge up a volley of soil\nRelease to fire the soil\n" +
are we putting a linebreak in the code for every linebreak in the tooltip or not? This is a bit weird to only split it on one of them

2025-01-17 02:12 UTC, ScalarVector1 commented on Content/Items/Misc/SoilgunFiles/Weapons.Soilgun.cs
> +			new AmmoStruct(ItemID.AshBlock, ModContent.ProjectileType<SoilgunAshSoil>(), "Inflicts On Fire!", 6),
Should use buff tooltips IE {{BUFF:OnFire}} if this emerges in an item tooltip

2025-01-17 02:12 UTC, ScalarVector1 commented on Content/Items/Misc/SoilgunFiles/Weapons.Soilgun.cs
> +		public bool CanHold => Owner.channel && !Owner.CCed && !Owner.noItems;
In general in the future try not to mix properties and fields like this, I generally try to do all fields then all properties

2025-01-17 02:12 UTC, ScalarVector1 commented on Content/Items/Misc/SoilgunFiles/Weapons.Soilgun.cs
> +			Texture2D tex = ModContent.Request<Texture2D>(Texture).Value;
Needs to switch to AssGen like all the others, in general you should never need to call ModContent.Request for textures now

2025-01-17 02:12 UTC, ScalarVector1 commented on Content/Items/Misc/SoilgunFiles/Weapons.SoilgunMiscProjectiles.cs
> -﻿using StarlightRiver.Core.Systems.CameraSystem;
Are these being deleted or not? If they're unused just delete this file

2025-01-17 02:12 UTC, ScalarVector1 commented on Content/Items/Misc/Weapons.Earthduster.cs
> +	public class EarthdusterDirtShot : EarthdusterProjectile
All the other multi ammo items have their projectiles in a seperate file it seems, why is this one condensed? That pattern seemed better given the large amount of small classes to be put together for the unique ammo projectiles

2025-01-17 02:12 UTC, ScalarVector1 commented on Content/Items/Vitric/Weapons.CoachGunUpgrade.cs
> +		public override void UseStyle(Player player, Rectangle heldItemFrame)
Is there a degree to which we can abstract some of this animation? Between all the guns looks like alot of reuse of similar effects. Perhaps there is some virtue in a gun base class or helper function for doing these animations?

2025-01-17 04:20 UTC, SkippZzMods commented on Content/Dusts/Glow.cs
> +	public class PixelatedGlow : ModDust
their behaviors are different yea

2025-02-02 02:55 UTC, ScalarVector1 approved these changes

2025-02-02 03:15 UTC, merged